

  default: &default
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    adapter: postgresql
  encoding: unicode
  database: your_database_name
  username: your_username
  password: your_password
  host: your_host
  port: your_port

development:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: protospace-40792

test:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: protospace-40792

production:
  <<: *default
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>
